### PR TITLE
eternal goals are not processed, they are ignored instead

### PR DESCRIPTION
**Pull request by wentz89**
https://github.com/opennars/OpenNARS-for-Applications/issues/99

### CODE REVIEW

**Comment by wentz89** [comment]
Since eternal goals are not supported and will not be in the future, I suggest to handle them differently the they are now. See https://github.com/opennars/OpenNARS-for-Applications/issues/99

**Review by patham9 — APPROVED** [review]
Thank you! This enhances usability, the handling to print a message instead of terminating the program is better in this case. Additionally I suggest puts("Warning: msg") instead of printf("msg\n"); , some compilers complain when using printf when puts suffices. Also "Warning: " will allow me to mark it as red in syntax highlighting (./NAR shell | python3 colorize.py), though if you prefer you can already merge then I'll do the message adjustment, in any case, the PR is approved now.

**Comment by wentz89** [comment]
You are welcome. As said in #99 , I just recently stumbled over NARS after a friend recommended it and i really think its great. So i want to use NARS in a research project that starts next year in the university department where i work (its about Learning from Demonstration for autonomous UAV's).
Anyway, now I'm just playing around and reading some of the papers.

**Comment by patham9** [comment]
Interesting, this sounds like a use case which should be well-supported by the "reasoner that can learn while operating" paradigm we are realizing with ONA. The upcoming v0.8.5 release will also contain the ROS (Robot Operating System) module plus first versions of channels for vision (via darknet) and landmark detection (visp_auto_tracker), which you might find useful. If you face any issues with the system we are happy to assist! Feel free to join us in the IRC or Google group especially. Out of curiosity, may I ask which university you are affiliated with? (you don't need to answer here, a PM in the IRC channel might be better)
Also: since your PR seems finished, feel free to merge it, else I can do later today.

**Comment by wentz89** [comment]
Sure I will contact you in the Google Group / IRC and Thanks for the offered assistance in case of issues :-)
By the way i couldn't have merged cause the panel said "only one with write access can merge".

**Pull request merged**
